l_english:
 DIVISION_QUEUED:0 "$N$ กองพล"
 DIVISIONS_QUEUED:0 "$N$ กองพล"
 CONVEYOR_EQUIPMENT_NEED:0 "ต้องการยุทโธปกรณ์:"
 CONVEYOR_MANPOWER_NEED:0 "ต้องการกำลังพล: $AMOUNT|H$"
 DEPLOYMENT_REQUIREMENT:0 "$NAME$: $AMOUNT$"
 DEPLOYMENT_DIVISION_LABEL:0 "กองพล"
 DEPLOYMENT_PROGRESS_LABEL:0 "ความคืบหน้า"
 DEPLOYMENT_PRIORITY_LABEL:0 "ลำดับความสำคัญ"
 DEPLOYMENT_DEPLOY_LABEL:0 "ประจำการ"
 DEPLOYMENT_TEMPLATE_ITEM_ADD:0 "§Gคลิกเพื่อเพิ่มการประจำการลงในคิว§!"
 DEPLOYMENT_TEMPLATE_ITEM_COPY:0 "§Gคลิกเพื่อคัดลอกไปยังแม่แบบของเราที่ใช้งานได้§!"
 DEPLOYMENT_TEMPLATE_ITEM_EDIT:0 "§Gคลิกเพื่อแก้ไขแม่แบบกองพล§!"
 DEPLOYMENT_TEMPLATE_ITEM_VIEW:0 "§Gคลิกเพื่อดูแม่แบบกองพล§!"
 DEPLOYMENT_TRAINING:0 "การฝึก: $VALUE|%Y0$ $MAXVALUE|$"
 DEPLOYMENT_TRAINING_MAXVALUE_DESC:0 "/ $VALUE|H%0$ ( ค่าประสบการณ์สูงสุดในตอนเริ่มประจำการขึ้นอยู่กับจำนวนยุทโธปกรณ์ )"
 DEPLOYMENT_CURRENT_LEVEL:0 "เลเวลของการประจำการคือ $NUMBER$ ( $LEVEL|%Y0$ )"
 DEPLOYMENT_MANPOWER_DESC:0 "กำลังพล: $VALUE|Y0$ ( สูงสุด $MAX|Y0$ )"
 DEPLOYMENT_EXPERIENCE_DESC:0 "\nถ้าการฝึกเสร็จแล้ว ยูนิตจะได้รับค่าประสบการณ์เลเวล $NUMBER$ ( $MAXLEVEL|%Y0$ ) มีผลต่อการรบ $EFFECT|+=%0$"
 DEPLOYMENT_EXPERIENCE_ESTIMATED_DESC:0 "\n ถ้ายูนิตในการฝึกมียุทโธปกรณ์ครบ จะฝึกเสร็จเมื่อ §Y$DATE$§!"
 DEPLOYMENT_EQUIPMENT:0 "ยุทโธปกรณ์: $VALUE|%Y0$"
 DEPLOYMENT_EQUIPMENT_FULL_DESC:0 "$NAME$: $VALUE|G0$/$MAX|G0$"
 DEPLOYMENT_EQUIPMENT_DESC:0 "$NAME$: $VALUE|Y0$/$MAX|Y0$"
 DEPLOYMENT_DESIGNER:0 "ออกแบบกองพล"
 DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT:0 "        $NAME|Y$: $VALUE|Y0$"
 DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT_FULL:0 "        $NAME|G$: $VALUE|G0$"
 DEPLOYMENT_EQUIPMENT_CHANGE:0 "$NAME$: $VALUE$"
 DEPLOYMENT_ADD_TEMPLATE:0 "ฝึก"
 DEPLOYMENT_LINES_HIT_THE_CAP:0 "เราสามารถฝึกได้มากที่สุด $CAP|*H$ คน\nรวมไปถึงกำลังพลสูงสุดในสนามรบ ( $RATIO|H0%$ จาก $INFIELD|*H$ ขั้นต่ำ: $MINPOSSIBLE|*H$ คน)"
 REGIMENTS_SELECTION_CANCEL:0 "กลับ"
 ONLY_ONE_TEMPLATE_LEFT:0 "คุณไม่สามารถลบแม่แบบสุดท้าย"
 DELETE_TEMPLATE:0 "§Rลบ§! แม่แบบจากรายการ"
 DELETE_TEMPLATE_TITLE:0 "ลบแม่แบบ"
 DELETE_TEMPLATE_DESC:0 "คุณแน่ใจหรือว่าต้องการลบแม่แบบนี้?"
 DEPLOYMENT_REMOVE_DIVISION:0 "ยกเลิกกองพล"
 DEPLOYMENT_DEPLOYMENT_LABEL:0 "เกณฑ์ทหารและประจำการ"
 DEPLOYMENT_NOT_ALLOWED_REASON_EQUIPMENT:0 "ไม่สามารถ §Rประจำการ§! ยูนิตที่ไม่มียุทโธปกรณ์ใดๆ\nโปรดรอจนกว่าจะได้รับยุทโธปกรณ์"
 DEPLOYMENT_NOT_ALLOWED_REASON_MANPOWER:0 "ไม่สามารถ §Rประจำการ§! ยูนิตที่มีมีกำลังพล"
 DEPLOYMENT_NOT_ALLOWED_REASON_TRAINING:0 "ไม่สามารถ §Rประจำการ§! ยูนิตต้องฝึกไปแล้วอย่างน้อย $VALUE|1H%$ (ตอนนี้ $CURRENT|1R%$)"
 DEPLOYMENT_NOT_ALLOWED_REASON_SPECIAL_FORCES:0 "ไม่สามารถ §Rประจำการ§! กำลังรบพิเศษมีจำนวนจำกัด"
 DEPLOYMENT_HOW_TO_DESC:0 "เลือกการประจำการจากรายการและจากนั้น §Gคลิก§! ในจังหวัดที่ไฮไลต์บนแผนที่เพื่อประจำการ\n§gยูนิตที่ประจำการแล้วแต่ยังรับยุทโธปกรณ์ไม่ครบจะร้องขอกำลังเสริม\nพิจารณาว่ายูนิตที่ประจำการอย่างเร่งรีบจะไม่ได้รับการฝึกอย่างเหมาะสม§!"
 OPERATIONS_DESC:0 "§Tกำหนดลำดับความสำคัญสำหรับยุทโธปกรณ์ที่จะเตรียมและดำเนินการปฏิบัติการ§!"
 OPERATIONS_EMPTY:0 "§Gไม่มีคำขอปัจจุบันสำหรับปฏิบัติการ§!"
 REINFORCEMENT:0 "การเสริมกำลัง"
 REINFORCEMENT_DESC:0 "§Tตั้งค่าลำดับความสำคัญยุทโธปกรณ์ที่จะใช้ในการเสริมกำลังทหารที่ปฏิบัติงานงานอยู่เทียบกับคิวประจำการและการอัปเกรด§!"
 REINFORCEMENT_EMPTY:0 "§Gไม่มีคำขอยุทโธปกรณ์§!"
 UPGRADES:0 "อัปเกรด"
 UPGRADES_DESC:0 "§Tตั้งค่าลำดับความสำคัญยุทโธปกรณ์ที่จะใช้ในการอัปเกรดกองกำลังปฏิบัติงานงานอยู่เทียบกับคิวประจำการและการอัปเกรด§!"
 UPGRADES_EMPTY:0 "§Gไม่มีคำขอการอัปเกรด§!"
 group_infantry_title:0 "กองพันทหารราบ"
 group_mobile_title:0 "กองพันเคลื่อนที่"
 group_armor_title:0 "กองพันยานเกราะ"
 group_support_title:1 "หน่วยสนับสนุน"
 NEW_GROUP_ADDITIONAL_COST:0 "กลุ่มใหม่ $VALUE|H0$£army_experience£"
 GARRISONS:0 "กองทหารรักษาการณ์"
 GARRISONS_DESC:0 "§Tกำหนดลำดับความสำคัญสำหรับยุทโธปกรณ์ที่จะเข้าประจำการในกองทหารรักษาการณ์§!"
 GARRISONS_EMPTY:0 "§Gไม่มีคำขอปัจจุบันสำหรับทหารรักษาการณ์§!"
 TIMED_ACTIVITY_TITLE:0 "$NAME$ ต่อต้าน $COUNTRY$"
 TIMED_ACTIVITY_ALERT_TITLE:0 "$NAME|H$ ต่อต้าน $COUNTRY|H$"
 TIMED_ACTIVITY_ENTRY_DESC:0 "§Tกำหนดลำดับความสำคัญสำหรับยุทโธปกรณ์ที่สนับสนุนกิจกรรมทางการทูตนี้§!"
 TIMED_ACTIVITY_ENTRY_COMPLETE_DESC:0 "§Gรวบรวมยุทโธปกรณ์ได้มากที่สุด§!"
 LAND_DEPLOYMENT:0 "§Tการประจำการหน่วยทหาร§!"
 AIR_DEPLOYMENT:0 "§Tการประจำการฝูงบิน§!"
 NAVAL_DEPLOYMENT:0 "§Tการประจำการกองเรือ§!"
 DIVISION_DESIGNER_RENAME:0 "เปลี่ยนชื่อ"
 DIVISION_DESIGNER_UPDATE:0 "ปรับปรุง"
 DEPLOY:0 "ประจำการ"
 EDIT:0 "แก้ไข"
 VIEW:0 "ดู"
 COPY:0 "คัดลอก"
 DIVISION_EQUIPMENT:1 "ยุทโธปกรณ์"
 NEW_EQUIPMENT_ALLOWED:0 "ใช้ยุทโธปกรณ์ใหม่"
 DO_NOT_CONTAINS_TEMPLATE:0 "§Rไม่สามารถลบแม่แบบนี้ ประเทศไม่มีแม่แบบนี้§!"
 HAS_ARMIES_WITH_TEMPLATE:0 "§Rไม่สามารถลบแม่แบบนี้เพราะ $AMOUNT|H$ กองพลกำลังใช้แม่แบบนี้อยู่§!"
 HAS_ARMIES_WITH_OLD_TEMPLATE:0 "§Rไม่สามารถลบแม่แบบนี้เพราะ $AMOUNT|H$ กองพลกำลังเปลี่ยนจากแม่แบบนี้เป็นแม่แบบใหม่ (รอรับยุทโธปกรณ์ที่ตรงกับแม่แบบใหม่)§!"
 HAS_DEPLOYMENT_CONVEYORS_WITH_TEMPLATE:0 "ไม่สามารถ §Rลบ§! แม่แบบจากประเทศนี้ ที่มี $AMOUNT|H$ ที่มีการประจำการที่ใช้แม่แบบนี้"
 HAS_GARRISON_WITH_TEMPLATE:0 "§Rไม่สามารถลบแม่แบบนี้ได้เนื่องจากมันถูกใช้เป็นแม่แบบของกองทหารรักษาการณ์ที่ใช้อยู่ในบางพื้นที่ที่ถูกยึดครอง§!"
 DEPLOYMENT_TEMPLATE_LABEL:0 "แม่แบบ"
 TEMPLATE_PRIO_0:0 "สำรอง"
 TEMPLATE_PRIO_0_DESC:0 "ยูนิตที่ใช้แม่แบบนี้จะได้รับยุทโธปกรณ์ช้าและลำดับความสำคัญต่ำที่สุดในการประจำการ เหมาะสำหรับหน่วยรักษาความปลอดภัยในแนวหลังเป็นต้น"
 TEMPLATE_PRIO_1:0 "ทั่วไป"
 TEMPLATE_PRIO_1_DESC:0 "ยูนิตที่ใช้แม่แบบนี้จะได้รับความสำคัญโดยเฉลี่ยสำหรับยุทโธปกรณ์และการเสริมกำลังเมื่อประจำการแล้ว"
 TEMPLATE_PRIO_2:0 "ขั้นสูง"
 TEMPLATE_PRIO_2_DESC:0 "ยูนิตที่ใช้แม่แบบนี้จะได้รับความสำคัญสูงสุดสำหรับยุทโธปกรณ์และการเสริมกำลังเมื่อประจำการแล้ว ใช้คนที่ดีที่สุดของคุณและที่พวกเขาสามารถทำได้ดีที่สุด"
 DEPLOYMENT_LEND_LEASE_COUNTRY:0 "ให้ยืม:$COUNTRY$"
 ADD_CONVEYOR_LINE_BUTTON_LABEL:0 "เพิ่มยูนิต"
 ADD_CONVEYOR_LINE_BUTTON_DESC:0 "เพิ่มยูนิตอื่นของ $CONVEYOR|H$ เพื่อผลิตในสายการผลิตแบบคู่ขนาน\n\n§GShift+คลิก§! เพื่อเพิ่ม 5 สาย"
 CONVEYOR_GENERIC_NAME_EDIT_DESC:0 "พิมพ์ที่นี่เพื่อเปลี่ยนชื่อทั่วไปของการประจำการ"
 CONVEYOR_TEMPLATE_ICON_DESC:0 "ในการสร้างกองพลที่ประจำการใช้แม่แบบ $TEMPLATE|H$"
 CANCEL_CONVEYOR_TOOLTIP:0 "§Rยกเลิก§! สายการผลิตของการประจำการทั้งหมด"
 DEPLOY_CONVEYOR_TOOLTIP:0 "§Gคลิก§! เพื่อประจำการทุกสายทันที"
 DEPLOY_CONVEYOR_DISABLED_TOOLTIP:0 "ยังไม่พร้อมกับการ §Rประจำการ§!"
 CONVEYOR_CANCEL_TITLE:0 "§Rยกเลิก§! การผลิต"
 CONVEYOR_CANCEL_DESC:0 "คุณแน่ใจหรือว่าต้องการ §Rยกเลิก§! การผลิตเพื่อการประจำการ?"
 CONVEYOR_LINE_CANCEL_DESC:0 "§Rยกเลิก§! สายการผลิตนี้"
 CONVEYOR_LINE_CANCEL_ACCEPT_TITLE:0 "§Rยกเลิก§! สายการประจำการ"
 CONVEYOR_LINE_CANCEL_ACCEPT_SINGLE_DESC:0 "คุณแน่ใจหรือว่าต้องการ §Rยกเลิก§! การผลิตในสายนี้?\n(การประจำการจะถูก §Rลบ§! ไปด้วย)"
 CONVEYOR_LINE_CANCEL_ACCEPT_DESC:0 "คุณแน่ใจหรือว่าต้องการ §Rยกเลิก§! การผลิตในสายนี้?"
 CONVEYOR_GROUP_ASSIGN_DESC:0 "§Gคลิก§! เพื่อระบุคำสั่งประจำการ\n§Gคลิกขวา§! เพื่อรีเซ็ตคำสั่ง"
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_ORDERS_DESC:0 "การประจำการควรมีคำสั่งอย่างน้อยหนึ่งคำสั่งภายในยุทธบริเวณที่จะกำหนดให้กับกลุ่มใดๆ"
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_LOCATION_DESC:0 "การประจำการควรมีตำแหน่งเป้าหมายที่จะกำหนดให้กับกลุ่มใดๆ"
 CONVEYOR_SET_LOCATION_DESC:0 "§Gคลิก§! เพื่อเลือกตำแหน่งที่ตั้งในการประจำการ\n§Gคลิกขวา§! เพื่อรีเซ็ตที่ตั้ง"
 CONVEYOR_SET_COLONIAL_LOCATION_DESC:0 "§Gคลิก§! เพื่อเลือกตำแหน่งที่ตั้งในการประจำการ\n§Gคลิกขวา§! เพื่อรีเซ็ตที่ตั้ง\n§Yนี่คือแม่แบบอาณานิคมและสามารถประจำการในประเทศต้นทางเท่านั้น!§!"
 CONVEYOR_SET_LOCATION_NOT_SET:0 "§Rไม่ได้กำหนดตำแหน่งที่ตั้ง§!"
 CONVEYOR_LINE_PREFIX_NAME_EDIT_DESC:0 "พิมพ์ที่นี่เพื่อเปลี่ยนคำนำหน้า"
 CONVEYOR_LINE_DEPLOY_DESC:0 "§Gคลิก§!เพื่อประจำการสายนี้ทันที"
 CONVEYOR_SERIES_INCREASE_DESC:0 "เพิ่มจำนวนการฝึกต่อเนื่องของกองพล\n\nการตั้งค่าเป็นไม่จำกัดหมายความว่าแต่ละสายเมื่อฝึกและประจำการเสร็จแล้วก็จะฝึกกองพลต่อไปเรื่อยๆ"
 CONVEYOR_SERIES_AMOUNT_DESC:0 "นี่คือจำนวนกองพลในแต่การฝึกก่อนที่จะถูกลบ\n\nการตั้งค่าเป็นไม่จำกัดหมายความว่าแต่ละสายเมื่อฝึกและประจำการเสร็จแล้วก็จะฝึกกองพลต่อไปเรื่อยๆ"
 CONVEYOR_SERIES_DECREASE_DESC:0 "ลดจำนวนการฝึกแบบต่อเนื่องของกองพล\n\nการตั้งค่าเป็นไม่จำกัดหมายความว่าแต่ละสายเมื่อฝึกและประจำการเสร็จแล้วก็จะฝึกกองพลต่อไปเรื่อยๆ"
 CONVEYOR_LOW_PRIORITY_DESC:0 "ลำดับความสำคัญต่ำในการเสริมกำลัง"
 CONVEYOR_MEDIUM_PRIORITY_DESC:0 "ลำดับความสำคัญปานกลางในการเสริมกำลัง"
 CONVEYOR_HIGH_PRIORITY_DESC:0 "ลำดับความสำคัญสูงในการเสริมกำลัง"
 CONVEYOR_CAN_NOT_TRAIN:0 "§Rยุทโธปกรณ์ไม่เพียงพอที่จะใช้ฝึก§!"
 CONVEYOR_CAN_NOT_MANPOWER_TRAIN:0 "§Rกำลังพลไม่เพียงพอที่จะฝึก§!"
 CONVEYOR_CAN_NOT_TRAIN_COUNT:1 "§Rกำลังพลหรือยุทโธปกรณ์ไม่เพียงพอที่จะฝึก $DIVS|H$ กองพล§!"
 CONVEYOR_COLLAPSE_DESC:0 "§Gคลิก§! เพื่อยุบ"
 CONVEYOR_EXPAND_DESC:0 "§Gคลิก§! เพื่อขยาย"
 CONVEYOR_MOVE_UP:0 "§Gคลิก§! เพื่อเลื่อนขึ้น\n§GShift+คลิก§! เพื่อเลื่อนไปบนสุด"
 CONVEYOR_MOVE_DOWN:0 "§Gคลิก§! เพื่อเลื่อนลง\n§GShift+คลิก§! เพื่อเลื่อนไปล่างสุด"
 DEPLOYMENT_LOW_PRIORITY_DESC:0 "ลำดับความสำคัญของยุทโธปกรณ์ต่ำ"
 DEPLOYMENT_MEDIUM_PRIORITY_DESC:0 "ลำดับความสำคัญของยุทโธปกรณ์ปานกลาง"
 DEPLOYMENT_HIGH_PRIORITY_DESC:0 "ลำดับความสำคัญของยุทโธปกรณ์สูง"
 CONVEYOR_HAS_BAD_LOCATION:0 "ตำแหน่งเป้าหมาย §Rเป็นไปไม่ได้§! ที่จะประจำการ"
 CONVEYOR_TRAINING_NOT_FINISHED:0 "การฝึกยังไม่เสร็จ"
 CONVEYOR_SERIES_CURRENT_AMOUNT_DESC:0 "เลขปัจจุบันในสายการประจำการ"
 CONVEYOR_LINE_SERIES_BASE:0 "$CURRENT$/$TARGET$"
 DEPLOYMENT_LINE_NAME_OVERRIDE_CANCEL:0 "§Hลบชื่อที่กำหนดเอง§!\nจะพยายามกลับไปใช้ชื่อดั้งเดิมที่ยังไม่ถูกใช้"
 DEPLOYMENT_LINE_CHOOSE_OTHER_NAME:0 "§Hเลือกชื่ออิงประวัติศาสตร์อื่น§!\n§Gคลิก§! เพื่อเปิดรายการชื่ออิงประวัติศาสตร์ที่ยังใช้งานได้ เป็นไปได้ที่จะเปลี่ยนกลุ่มชื่อโดยแก้ไขแม่แบบ"
 DEPLOYMENT_LINE_EDIT_NAME:0 "§Gคลิก§! และพิมพ์เพื่อใช้ชื่อที่กำหนดเอง"
 DEPLOYMENT_LINE_OUT_OF_NAMES:0 "§gไม่มีชื่ออิงประวัติศาสตร์§!"
 MISSING_SPECIAL_FORCES_CAP:0 "§Rกำลังรบพิเศษไม่เพียงพอ§!"
 TRAINING_HALTED:0 "หยุดการฝึก\n"
 CANNOT_DELETE_SPECIAL_TEMPLATES:0 "ไม่สามารถลบแม่แบบพิเศษ"
 DEPLOYMENT_CANNOT_TRAIN_SPECIAL_UNITS:1 "ไม่สามารถฝึกกองพลแม่แบบพิเศษใหม่"
 DEPLOYMENT_EXILE_WITH_NO_CAPITAL:0 "§Hรัฐบาลพลัดถิ่น§! เราต้องควบคุม §Hเมืองหลวง§! เพื่อฝึกกองพลใหม่"
 CANT_CHANGE_DUE_TO_SPECIAL_FORCES_CAP:0 "ไม่สามารถเปลี่ยนเป็นแม่แบบนี้ได้เพราะนั่นจะทำให้จำนวนกำลังรบพิเศษของเราเกินกำหนด"
 NO_SPECIAL_FORCES:0 "แม่แบบนี้ไม่มีกองกำลังพิเศษใดๆ"
 SPECIAL_FORCES_IN_TEMPLATE:0 "แม่แบบนี้มี $NUM|Y$ กองพันรบพิเศษ"
 SPECIAL_FORCES_CAP_DESC:0 "คุณกำลังใช้ $USED|Y$ และกำลังฝึก $IN_TRAINING|Y$ เกิน $CAP|Y$ กำหนดของกองพันรบพิเศษ"
 DEPLOYMENT_MAX_DEPLOYABLE_DIVISION_FOR_TEMPLATE:0 "สามารถฝึกได้ $TRAINABLE|Y$ กองพลที่กำลังใช้แม่แบบนี้"
